/* eslint-disable */
export const MENU_ACTIVE = 'MENU_ACTIVE'

export const NEWS_MOST_RECENT = 'NEWS_MOST_RECENT'

export const NEWEST_PRODUCTS = 'NEWEST_PRODUCTS'

export const ADD_ITEM_TO_SHOPPING_CART = 'ADD_ITEM_TO_SHOPPING_CART'
